### ISSUE TITLE
[AssetsReports] Be fails

### ISSUE THREAD

**Issue by turulomio** [turulomio/django_moneymoney#113]

**Comment by turulomio** [comment]
[Thu Apr 11 04:24:25.195830 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952] Not Found: /django_moneymoney/reports/annual/gainsbyproductstypes/2024/
[Thu Apr 11 04:24:25.220958 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952] Internal Server Error: /django_moneymoney/assets/report/
[Thu Apr 11 04:24:25.220985 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952] Traceback (most recent call last):
[Thu Apr 11 04:24:25.220987 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952]   File "/var/www/localhost/htdocs/django_moneymoney/.python3.11/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
[Thu Apr 11 04:24:25.220988 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952]     response = get_response(request)
[Thu Apr 11 04:24:25.220990 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952]                ^^^^^^^^^^^^^^^^^^^^^
[Thu Apr 11 04:24:25.220991 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952]   File "/var/www/localhost/htdocs/django_moneymoney/.python3.11/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
[Thu Apr 11 04:24:25.220993 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Thu Apr 11 04:24:25.220994 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Thu Apr 11 04:24:25.220995 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952]   File "/var/www/localhost/htdocs/django_moneymoney/.python3.11/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
[Thu Apr 11 04:24:25.220997 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952]     return view_func(request, *args, **kwargs)
[Thu Apr 11 04:24:25.221008 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Thu Apr 11 04:24:25.221009 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952]   File "/var/www/localhost/htdocs/django_moneymoney/.python3.11/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
[Thu Apr 11 04:24:25.221010 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952]     return self.dispatch(request, *args, **kwargs)
[Thu Apr 11 04:24:25.221011 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Thu Apr 11 04:24:25.221012 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952]   File "/var/www/localhost/htdocs/django_moneymoney/.python3.11/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
[Thu Apr 11 04:24:25.221013 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952]     response = self.handle_exception(exc)
[Thu Apr 11 04:24:25.221014 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952]                ^^^^^^^^^^^^^^^^^^^^^^^^^^
[Thu Apr 11 04:24:25.221015 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952]   File "/var/www/localhost/htdocs/django_moneymoney/.python3.11/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
[Thu Apr 11 04:24:25.221016 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952]     self.raise_uncaught_exception(exc)
[Thu Apr 11 04:24:25.221016 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952]   File "/var/www/localhost/htdocs/django_moneymoney/.python3.11/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
[Thu Apr 11 04:24:25.221017 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952]     raise exc
[Thu Apr 11 04:24:25.221018 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952]   File "/var/www/localhost/htdocs/django_moneymoney/.python3.11/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
[Thu Apr 11 04:24:25.221019 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952]     response = handler(request, *args, **kwargs)
[Thu Apr 11 04:24:25.221020 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Thu Apr 11 04:24:25.221021 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952]   File "/var/www/localhost/htdocs/django_moneymoney/.python3.11/lib/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
[Thu Apr 11 04:24:25.221022 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952]     return func(*args, **kwargs)
[Thu Apr 11 04:24:25.221023 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952]            ^^^^^^^^^^^^^^^^^^^^^
[Thu Apr 11 04:24:25.221024 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952]   File "/var/www/localhost/htdocs/django_moneymoney/moneymoney/views.py", line 89, in AssetsReport
[Thu Apr 11 04:24:25.221025 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952]     filename=generate_assets_report(request, format_, test)
[Thu Apr 11 04:24:25.221026 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Thu Apr 11 04:24:25.221027 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952]   File "/var/www/localhost/htdocs/django_moneymoney/moneymoney/assetsreport.py", line 53, in generate_assets_report
[Thu Apr 11 04:24:25.221028 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952]     dict_report_annual_gainsbyproductstypes=client.get(reverse('ReportAnnualGainsByProductstypes', args=(year,  )), **language_headers).json()
[Thu Apr 11 04:24:25.221029 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952]                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Thu Apr 11 04:24:25.221030 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952]   File "/var/www/localhost/htdocs/django_moneymoney/.python3.11/lib/python3.11/site-packages/django/test/client.py", line 882, in _parse_json
[Thu Apr 11 04:24:25.221033 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952]     raise ValueError(
[Thu Apr 11 04:24:25.221033 2024] [wsgi:error] [pid 26788] [remote 127.0.0.1:47952] ValueError: Content-Type header is "text/html; charset=utf-8", not "application/json"
